---
- hosts: all
  name: cis-91 project 1 dokuwiki
  become: yes
  tasks:

    - name: format storage
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-data_disk

    - name: mount storage
      ansible.posix.mount:
        boot: yes
        fstype: ext4
        path: /var/www
        src: /dev/disk/by-id/google-data_disk
        state: mounted

    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2 
          - php
          - php-xml

    - name: unarchive dokuwiki
      ansible.builtin.unarchive:
        remote_src: yes
        src: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /var/www/html
        owner: www-data
        extra_opts: --strip-components=1

    - name: add backup script
      ansible.builtin.copy:
        remote_src: yes
        src: https://raw.githubusercontent.com/cTurtle98/cis-91/main/dokuwiki/backup.sh
        dest: /etc/cron.hourly/backup
        owner: root
        group: root
        mode: u+rwx